---
title: Andrew Tran Github page
date: 2019-03-01
---
author: Andrew Tran
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Electrical Engineering and Computer Science major!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
